version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    container_name: server
    ports:
      - "5000:5000"
    networks:
      - app-network
  
networks:
    app-network:
        driver: bridge
        